/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package SpeedClick;

import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.JOptionPane;

/**
 *
 * @author bapti
 */
public class FenetreAccueil extends javax.swing.JFrame {

    /**
     * Creates new form FenetreAccueil
     */
    public FenetreAccueil() {
        initComponents();

        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setSize(800, 500);
        setLocationRelativeTo(null);

        // Crée un JLayeredPane pour gérer les couches
        JLayeredPane layeredPane = new JLayeredPane();
        setContentPane(layeredPane);

        // Ajoute l'image de fond en tant que JLabel
        ImageIcon imageFond = new ImageIcon("C:\\Users\\bapti\\Documents2\\2A\\CPO_MINI_PROJET2\\SPEED-CLICK\\src\\SpeedClick\\Image1.jpg");
        Image image = imageFond.getImage().getScaledInstance(800, 500, Image.SCALE_SMOOTH);
        ImageIcon imageFondScaled = new ImageIcon(image);
        JLabel labelFond = new JLabel(imageFond);
        labelFond.setBounds(0, 0, 800, 500);
        layeredPane.add(labelFond, Integer.valueOf(0));  // Ajoute à la couche de fond

        // Ajoute un JLabel pour le texte
        JLabel labelTexte = new JLabel("BIENVENUE SUR SPEEDY GONZALEZ CLICK");
        labelTexte.setForeground(Color.RED);  // Couleur du texte
        labelTexte.setFont(new Font("Arial", Font.BOLD, 24));  // Style et taille de police
        labelTexte.setBounds(50, 50, 600, 50);  // Position et taille du label
        layeredPane.add(labelTexte, Integer.valueOf(1));  // Ajoute à la couche au-dessus du fond

        // Ajoute un bouton cliquable
        JButton bouton = new JButton("Cliquez-moi !");
        bouton.setBounds(100, 100, 150, 30);
        layeredPane.add(bouton, Integer.valueOf(2));  // Ajoute à la couche au-dessus du texte
        bouton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // Le code ici sera exécuté lorsque le bouton est cliqué
                
                new FenetrePrincipale().setVisible(true);
                fermerFenetre();

            }
        });

        setVisible(true);

    }
    
    private void fermerFenetre() {
        // Ferme la fenêtre actuelle
        this.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(450, 220, 500, 500));
        setPreferredSize(new java.awt.Dimension(730, 415));
        setSize(new java.awt.Dimension(500, 300));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FenetreAccueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FenetreAccueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FenetreAccueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FenetreAccueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FenetreAccueil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
